<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic.SDK" Version="5.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobSearch.Application.Abstractions\JobSearch.Application.Abstractions.csproj" />
    <ProjectReference Include="..\JobSearch.Persistence.Abstractions\JobSearch.Persistence.Abstractions.csproj" />
    <ProjectReference Include="..\JobSearch.Scraping\JobSearch.Scraping.csproj" />
  </ItemGroup>

</Project>
